name: "publish"
on:
  push:
    tags: "v*"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v1
      - name: "Run test"
        run: make
  publish:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: "Checkout"
        id: "checkout"
        uses: actions/checkout@v1
      - name: "Build report"
        id: "build"
        run: make
      - name: "Create release"
        id: "create_release"
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
      - name: "Upload release asset"
        id: "upload_release_asset"
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./report.pdf
          asset_name: report.pdf
          asset_content_type: application/pdf
